package sistem.pakar;

import sistem.pakar.kelas_tanmbahan.koneksi;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

public class diagnosa_langsung2 extends javax.swing.JDialog {
String a="tidak";
String b="tidak";
String c="tidak";
String d="tidak";
String e="tidak";
String f="tidak";
String g="tidak";
String hi="tidak";
String j="tidak";
String i="tidak";
String k="tidak";

String diagnosa_akhir="penyakit tanaman anda :\n- ";
String diagnosa_akhir1="Penjelasan :\n- ";
String diagnosa_akhir2="Pengendalian :\n- ";
String diagnosa_lanjut;


    
    public diagnosa_langsung2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setText("ID Tanaman");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 255, 255));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel9.setText("Nama Tanaman");

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        jRadioButton1.setText("coklat");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jRadioButton2.setText("coklat muda");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 85, -1, -1));

        jRadioButton3.setText("seperti biasa");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jRadioButton4.setText("tidak");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 157, -1, -1));

        jRadioButton5.setText("ya");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jRadioButton6.setText("tidak");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 228, -1, -1));

        jRadioButton7.setText("ya");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jRadioButton8.setText("tidak");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 301, -1, -1));

        jRadioButton9.setText("ya");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jRadioButton10.setText("tidak");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jRadioButton15.setText("ya");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jRadioButton11.setText("ya");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        jRadioButton12.setText("tidak");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 74, -1, -1));

        jRadioButton13.setText("ya");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jRadioButton14.setText("tidak");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jRadioButton17.setText("ya");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jRadioButton18.setText("ungu tua pusat coklat putih");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jRadioButton19.setText("coklat merah pusat coklat merah/kuning");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jRadioButton20.setText("ungu berbentuk telur");
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jRadioButton21.setText("coklat hitam");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jRadioButton22.setText("abu-abu dikelilingi merah ungu berbentuk V");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton22ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, 340, 10));

        jButton1.setText("Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 131, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         if(jTextField2.getText()=="Stroberi"){
             a="coklat";
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton7.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton8.setEnabled(false);
         }else if(jTextField2.getText()=="Jeruk"){
             a=jRadioButton1.getText();
             jRadioButton2.setSelected(false);
             jRadioButton3.setSelected(false);
             jRadioButton4.setSelected(false);
             jRadioButton6.setSelected(false);
             jRadioButton7.setEnabled(true);
             jRadioButton5.setEnabled(true);
         }else{
             a=jRadioButton1.getText();
             jRadioButton2.setSelected(false);
         }
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jTextField2.getText()=="Stroberi"){
            a="coklat muda";
        jRadioButton1.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton5.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton7.setEnabled(true);
        jRadioButton6.setEnabled(true);
        jRadioButton9.setEnabled(true);
        jRadioButton8.setEnabled(true);
        }else if(jTextField2.getText()=="Jeruk"){
             a=jRadioButton2.getText();
             jRadioButton1.setSelected(false);
             jRadioButton3.setSelected(false);
             jRadioButton7.setEnabled(true);
             jRadioButton5.setEnabled(true);
             jRadioButton4.setSelected(false);
             jRadioButton6.setSelected(false);
         }else{
            a=jRadioButton2.getText();
            jRadioButton1.setSelected(false);
        }
        
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
       if(jTextField2.getText()=="Stroberi"){
           a="seperti biasa";
        
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton5.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton8.setEnabled(false);
       }else if(jTextField2.getText()=="Jeruk"){
             a=jRadioButton3.getText();
             jRadioButton2.setSelected(false);
             jRadioButton1.setSelected(false);
             jRadioButton4.setSelected(true);
             jRadioButton6.setSelected(true);
             jRadioButton7.setEnabled(false);
             jRadioButton5.setEnabled(false);
         }else{
           
       }
        
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        b="tidak";
        jRadioButton5.setSelected(false);
       

    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
       b="ya";
        jRadioButton4.setSelected(false);  

    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        c="tidak";
        jRadioButton7.setSelected(false);

    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        c="ya";
        jRadioButton6.setSelected(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
         if(jTextField2.getText()=="Stroberi"){
             d="tidak";
            jRadioButton9.setSelected(false);
         }else if(jTextField2.getText()=="Jeruk"){
             d="tidak";
             jRadioButton9.setSelected(false);
             jRadioButton10.setSelected(true);
             jRadioButton11.setEnabled(false);
             
         }else{
             d="tidak";
             jRadioButton9.setSelected(false);
         }
         
        
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        d="ya";
        jRadioButton8.setSelected(false);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        e="tidak";
        jRadioButton11.setSelected(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        
        f="tidak";
        jRadioButton13.setSelected(false);
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed

        f="ya";
        jRadioButton12.setSelected(false);
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
       if(jTextField2.getText()=="Stroberi"){
           g="tidak";
        jRadioButton17.setSelected(false);
        jRadioButton18.setEnabled(false);
        jRadioButton19.setEnabled(false);
        jRadioButton20.setEnabled(false);
        jRadioButton21.setEnabled(false);
        jRadioButton22.setEnabled(false);
       }else if(jTextField2.getText()=="Jeruk"){
           g="tidak";
           jRadioButton17.setSelected(false);
       }
        
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        if(jTextField2.getText()=="Stroberi"){
          g="ya";
        jRadioButton14.setSelected(false);
        jRadioButton18.setEnabled(true);
        jRadioButton19.setEnabled(true);
        jRadioButton20.setEnabled(true);
        jRadioButton21.setEnabled(true);
        jRadioButton22.setEnabled(true);
        }else if(jTextField2.getText()=="Jeruk"){
           g="ya"; 
           jRadioButton14.setSelected(false);
        }else{
            
        }
        
        
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
       if(jTextField2.getText()=="Stroberi"){
           hi="ungu tua pusat coklat putih";
        jRadioButton20.setSelected(false);
        jRadioButton19.setSelected(false);
        jRadioButton21.setSelected(false);
        jRadioButton22.setSelected(false);
       }else if(jTextField2.getText()=="Jeruk"){
           hi=jRadioButton18.getText();
           jRadioButton20.setSelected(false);
       }else{
           hi=jRadioButton18.getText();
           jRadioButton20.setSelected(false);
       }
        
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        if(jTextField2.getText()=="Stroberi"){
            hi="coklat merah pusat coklat merah/kuning";
        jRadioButton20.setSelected(false);
        jRadioButton18.setSelected(false);
        jRadioButton21.setSelected(false);
        jRadioButton22.setSelected(false);
        }else if(jTextField2.getText()=="Jeruk"){
            j=jRadioButton19.getText();
            jRadioButton21.setSelected(false);
            jRadioButton22.setSelected(false);
        }else{
            
        }
        
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        if(jTextField2.getText()=="Stroberi"){
            hi="ungu berbentuk telur";
        jRadioButton18.setSelected(false);
        jRadioButton21.setSelected(false);
        jRadioButton22.setSelected(false);
        jRadioButton19.setSelected(false);
        }else if(jTextField2.getText()=="Jeruk"){
            hi=jRadioButton20.getText();
            jRadioButton18.setSelected(false);
        }else{
            hi=jRadioButton20.getText();
            jRadioButton18.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            koneksi con=new koneksi();
            Hasil h=new Hasil(null,true);
            String[] d1=new String[1000];
            String[] d2=new String[1000];
            String[] d3=new String[1000];
            con.setkoneksi();
            if(jTextField2.getText().equals("Stroberi")){
                con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where\n" +
"d.j22='"+a+"' and d.j14='"+b+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
            if(con.rs.next()){
                d1[0]=con.rs.getString(1);
                d2[0]=con.rs.getString(2);
                d3[0]=con.rs.getString(3);
            }
           con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where\n" +
"d.j22='"+a+"' and d.j15='"+c+"' and d.j16='"+d+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
           if(con.rs.next()){
                d1[1]=con.rs.getString(1);
                d2[1]=con.rs.getString(2);
                d3[1]=con.rs.getString(3);
            }
           con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where\n" +
"d.j17='"+e+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
           if(con.rs.next()){
                d1[2]=con.rs.getString(1);
                d2[2]=con.rs.getString(2);
                d3[2]=con.rs.getString(3);
            }
           con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where\n" +
"d.j18='"+f+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
           if(con.rs.next()){
                d1[3]=con.rs.getString(1);
                d2[3]=con.rs.getString(2);
                d3[3]=con.rs.getString(3);
            }
            con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where\n" +
"d.j19='"+g+"' and j20='"+hi+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
             if(con.rs.next()){
                d1[4]=con.rs.getString(1);
                d2[4]=con.rs.getString(2);
                d3[4]=con.rs.getString(3);
            }
           for(int i=0;i<5;i++){
               if((d1[i]!=null) && (d2[i]!=null) && (d3[i]!=null)){
                    diagnosa_akhir=diagnosa_akhir+d1[i]+"\n- ";
                diagnosa_akhir1=diagnosa_akhir1+d2[i]+"\n- ";
                diagnosa_akhir2=diagnosa_akhir2+d3[i]+"\n- ";
               }}}else if(jTextField2.getText()=="Jeruk"){
                   con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where \n" +
"d.j22='"+a+"'and d.j15='"+c+"' and d.j18='"+f+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                if(con.rs.next()){
                d1[0]=con.rs.getString(1);
                d2[0]=con.rs.getString(2);
                d3[0]=con.rs.getString(3);
            }
                   con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where \n" +
"d.j22='"+a+"'and d.j14='"+b+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                if(con.rs.next()){
                d1[1]=con.rs.getString(1);
                d2[1]=con.rs.getString(2);
                d3[1]=con.rs.getString(3);
            }
                con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where \n" +
"d.j16='"+d+"'and d.j17='"+e+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                if(con.rs.next()){
                d1[2]=con.rs.getString(1);
                d2[2]=con.rs.getString(2);
                d3[2]=con.rs.getString(3);
            }
                con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where \n" +
"d.j19='"+g+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                if(con.rs.next()){
                d1[3]=con.rs.getString(1);
                d2[3]=con.rs.getString(2);
                d3[3]=con.rs.getString(3);
            }
                 con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where \n" +
"d.j21='"+hi+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                 if(con.rs.next()){
                d1[4]=con.rs.getString(1);
                d2[4]=con.rs.getString(2);
                d3[4]=con.rs.getString(3);
            }
                 con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit where \n" +
"d.j23='"+j+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                 if(con.rs.next()){
                d1[5]=con.rs.getString(1);
                d2[5]=con.rs.getString(2);
                d3[5]=con.rs.getString(3);
            }
                 
                   for(int j=0;j<6;j++){
                      if((d1[j]!=null) && (d2[j]!=null) && (d3[j]!=null)){
                diagnosa_akhir=diagnosa_akhir+d1[j]+"\n- ";
                diagnosa_akhir1=diagnosa_akhir1+d2[j]+"\n- ";
                diagnosa_akhir2=diagnosa_akhir2+d3[j]+"\n- ";
                }
                   }
                   
               }else{
                   con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit\n" +
"where d.j7='"+a+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                    if(con.rs.next()){
                d1[0]=con.rs.getString(1);
                d2[0]=con.rs.getString(2);
                d3[0]=con.rs.getString(3);
            }
                    con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit\n" +
"where d.j8='"+b+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                    if(con.rs.next()){
                d1[1]=con.rs.getString(1);
                d2[1]=con.rs.getString(2);
                d3[1]=con.rs.getString(3);
               }
                    con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit\n" +
"where d.j9='"+c+"' and d.j10='"+d+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                   if(con.rs.next()){
                d1[2]=con.rs.getString(1);
                d2[2]=con.rs.getString(2);
                d3[2]=con.rs.getString(3);
               } 
                   con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit\n" +
"where d.j11='"+e+"' and d.j12='"+f+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                   if(con.rs.next()){
                d1[3]=con.rs.getString(1);
                d2[3]=con.rs.getString(2);
                d3[3]=con.rs.getString(3);
               } 
                   con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit\n" +
"where d.j14='"+g+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                    if(con.rs.next()){
                d1[4]=con.rs.getString(1);
                d2[4]=con.rs.getString(2);
                d3[4]=con.rs.getString(3);
               }
                    con.rs=con.st.executeQuery("select p.nm_penyakit,p.penjelasan,p.obat from diagnosa_tanaman d inner join penyakit p on d.Kd_penyakit=p.Kd_penyakit\n" +
"where d.j15='"+hi+"' and d.ID_Tanaman='"+jTextField3.getText()+"'");
                    if(con.rs.next()){
                d1[5]=con.rs.getString(1);
                d2[5]=con.rs.getString(2);
                d3[5]=con.rs.getString(3);
               }
                   for(int j=0;j<6;j++){
                      if((d1[j]!=null) && (d2[j]!=null) && (d3[j]!=null)){
                diagnosa_akhir=diagnosa_akhir+d1[j]+"\n- ";
                diagnosa_akhir1=diagnosa_akhir1+d2[j]+"\n- ";
                diagnosa_akhir2=diagnosa_akhir2+d3[j]+"\n- ";
               }
                   }
               }
               
               

            
            h.gettext().setText(diagnosa_akhir);
            h.gettext1().setText(diagnosa_akhir1);
            h.gettext2().setText(diagnosa_akhir2);
            h.gettxt().setText(jTextField3.getText());
            h.gettxt1().setText(jTextField2.getText());
            con.st.execute("insert into Hasil values('"+jTextField3.getText()+"','"+jTextField2.getText()+"','"+diagnosa_akhir+"','"+diagnosa_akhir1+"','"+diagnosa_akhir2+"')");
            h.setVisible(true);
            this.dispose();
            
            

        } catch (SQLException ex) {
            Logger.getLogger(diagnosa_langsung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton21ActionPerformed
        if(jTextField2.getText()=="Stroberi"){ 
            hi="coklat hitam";
        jRadioButton18.setSelected(false);
        jRadioButton19.setSelected(false);
        jRadioButton20.setSelected(false);
        jRadioButton22.setSelected(false);
        }else{
            j=jRadioButton21.getText();
            jRadioButton19.setSelected(false);
            jRadioButton22.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButton21ActionPerformed

    private void jRadioButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton22ActionPerformed
        if(jTextField2.getText()=="Stroberi"){
            hi="abu-abu dikelilingi merah ungu berbentuk V";
        jRadioButton18.setSelected(false);
        jRadioButton19.setSelected(false);
        jRadioButton20.setSelected(false);
        jRadioButton21.setSelected(false);
        }else{
            j=jRadioButton22.getText();
            jRadioButton19.setSelected(false);
            jRadioButton21.setSelected(false);
        }
        
    }//GEN-LAST:event_jRadioButton22ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        e="ya";
        jRadioButton10.setSelected(false);
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagnosa_langsung2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagnosa_langsung2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagnosa_langsung2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagnosa_langsung2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagnosa_langsung2 dialog = new diagnosa_langsung2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
public JTextField jtext1(){
        return jTextField2;
    }
    public JTextField jtext(){
        return jTextField3;
    }
    public JLabel jlabel1(){
        return jLabel1;
    }
    public JLabel jlabel2(){
        return jLabel2;
    }
    public JLabel jlabel3(){
        return jLabel3;
    }
    public JLabel jlabel4(){
        return jLabel4;
    }
    public JLabel jlabel5(){
        return jLabel5;
    }
    public JLabel jlabel6(){
        return jLabel6;
    }
    public JLabel jlabel7(){
        return jLabel7;
    }
     public JLabel jlabel11(){
        return jLabel11;
    }
     public JLabel jlabel12(){
        return jLabel10;
    }
     public JRadioButton jpilih(){
         return jRadioButton1;
     }
     public JRadioButton jpilih1(){
         return jRadioButton2;
     }
     public JRadioButton jpilih2(){
         return jRadioButton3;
     }
     public JRadioButton jpilih3(){
         return jRadioButton20;
     }
     public JRadioButton jpilih4(){
         return jRadioButton18;
     }
     public JRadioButton jpilih5(){
         return jRadioButton19;
     }
      public JRadioButton jpilih6(){
         return jRadioButton21;
     }
       public JRadioButton jpilih7(){
         return jRadioButton22;
     }
    
}
