/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistem.pakar;

import sistem.pakar.kelas_tanmbahan.pengiriman_nilai;
import sistem.pakar.kelas_tanmbahan.koneksi;
import static java.awt.SystemColor.info;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author Ncef
 */
public class FormDiagnosa extends javax.swing.JFrame {

        String ya="ya";
        String no="tidak";
        String nama;
        //String[] data=new String[50];
        int i=0;
        pengiriman_nilai n=new pengiriman_nilai();
        diagnosa_langsung diagnosa = new diagnosa_langsung(this,true);
        diagnosa_langsung2 di = new diagnosa_langsung2(this,true);
        
        
    public void tampilcom() {
       
        try {
            koneksi con = new koneksi();
            con.setkoneksi();
            con.rs = con.st.executeQuery("select * from tanaman");
            while(con.rs.next()){
                String Nama = con.rs.getString(3);
                Pilihan.addItem(Nama);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormDiagnosa.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public JPanel panel1(){
    return jPanel2;
}
    
    public FormDiagnosa() {
        initComponents();
        tampilcom();
        setResizable(false);
        jTextField1.setEnabled(false);
        n.getKirim();
        //Pilihan1.setEnabled(false);
        //NamaT1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Pilihan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Apakah Tanaman anda berwarna coklat ?");

        jButton1.setText("YA");

        jButton2.setText("TIDAK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel8)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Apakah daun anda normal ?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(188, 188, 188))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Apakah daun anda berwarna kuning berbercak kuning ?");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(107, 107, 107))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Apakah pucuk daun tanaman anda kriput atau kriting ?");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel11)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel12.setText("Apakah ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel12)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Apakah tanaman berbunga ?");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel13)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel13)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("apakah tanaman anda lama untuk berbunga atau berbuah ?");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(102, 102, 102))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDT (Sistem Pakar Tanaman)");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nama Tanaman :");

        Pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---pilih---" }));
        Pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("ID Tanaman");

        jLabel6.setText(":");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sample Pictures/Doctor-icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Silahkan diagnosa tanaman anda !!");

        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setText("Hama");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Diagnosa");

        jButton3.setText("Penyakit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton3))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Pilihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                                .addGap(0, 86, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(56, 320, Short.MAX_VALUE)))
                        .addComponent(jLabel5))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihanActionPerformed
            try {
                koneksi con = new koneksi();
                con.setkoneksi();
                con.rs=con.st.executeQuery("select * from tanaman where Nama_Tanaman='"+Pilihan.getSelectedItem()+"'");
                if(con.rs.next()){
                    if(Pilihan.getSelectedItem().equals("Stroberi")){
                        jTextField1.setText(con.rs.getString(1));
                    nama=(String) Pilihan.getSelectedItem();
                    jButton6.setEnabled(true);
                    }else if(Pilihan.getSelectedItem().equals("Bunga Melati")){
                        jTextField1.setText(con.rs.getString(1));
                    nama=(String) Pilihan.getSelectedItem();
                    jButton6.setEnabled(true);
                    }else{
                        jTextField1.setText(con.rs.getString(1));
                    nama=(String) Pilihan.getSelectedItem();
                    jButton6.setEnabled(false);
                    }
                    
                }   } catch (SQLException ex) {
                Logger.getLogger(FormDiagnosa.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_PilihanActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            try {
                Pilihan.setEnabled(false);
                
               
                koneksi con=new koneksi();
                con.setkoneksi();
                if(Pilihan.getSelectedItem().equals("Stroberi")){
                int level=1;
                con.rs=con.st.executeQuery("select p.ID_Tanaman,t.Nama_Tanaman,p.Pertanyaanke_1,p.Pertanyaanke_2,p.Pertanyaanke_3,p.Pertanyaanke_4,p.Pertanyaanke_5,p.Pertanyaanke_6,p.Pertanyaanke_7,p.Pertanyaanke_8,p.Pertanyaanke_9,p.Pertanyaanke_10,p.Pertanyaanke_11,p.Pertanyaanke_12 from tanaman t inner join pertanyaan p on t.ID_Tanaman=p.ID_Tanaman where p.ID_Tanaman='"+jTextField1.getText()+"' and p.Kd_Pertanyaan='"+level+"'");
                if(con.rs.next()){
                 
                 diagnosa.jlabel1().setText(con.rs.getString(3));
                 diagnosa.jlabel2().setText(con.rs.getString(4));
                 diagnosa.jlabel3().setText(con.rs.getString(5));
                 diagnosa.jlabel4().setText(con.rs.getString(6));
                 diagnosa.jlabel5().setText(con.rs.getString(7));
                 diagnosa.jlabel6().setText(con.rs.getString(8));
                 diagnosa.jlabel7().setText(con.rs.getString(9));
                 diagnosa.jlabel11().setText(con.rs.getString(10));
                 diagnosa.jlabel12().setText(con.rs.getString(11));
                 diagnosa.jlabel13().setText(con.rs.getString(12));
                 diagnosa.jlabel14().setText(con.rs.getString(13));
                 diagnosa.jlabel15().setText(con.rs.getString(14));
                 diagnosa.jtext().setText(con.rs.getString(1));
                 diagnosa.jtext1().setText(con.rs.getString(2));
                 diagnosa.setVisible(true);
                 dispose();
                }
                }else if(Pilihan.getSelectedItem().equals("Bunga Melati")){
                   int level=5;
                con.rs=con.st.executeQuery("select p.ID_Tanaman,t.Nama_Tanaman,p.Pertanyaanke_1,p.Pertanyaanke_2,p.Pertanyaanke_3,p.Pertanyaanke_4,p.Pertanyaanke_5,p.Pertanyaanke_6,p.Pertanyaanke_7,p.Pertanyaanke_8,p.Pertanyaanke_9,p.Pertanyaanke_10,p.Pertanyaanke_11,p.Pertanyaanke_12 from tanaman t inner join pertanyaan p on t.ID_Tanaman=p.ID_Tanaman where p.ID_Tanaman='"+jTextField1.getText()+"' and p.Kd_Pertanyaan='"+level+"'");
                if(con.rs.next()){
                 
                 diagnosa.jlabel1().setText(con.rs.getString(3));
                 diagnosa.jlabel2().setText(con.rs.getString(4));
                 diagnosa.jlabel3().setText(con.rs.getString(5));
                 diagnosa.jlabel4().setText(con.rs.getString(7));
                 diagnosa.jlabel5().setText(con.rs.getString(8));
                 diagnosa.jlabel6().setText(con.rs.getString(6));
                 diagnosa.jlabel7().setText(con.rs.getString(9));
                 diagnosa.jlabel11().setText(con.rs.getString(10));
                 diagnosa.jlabel12().setText(con.rs.getString(11));
                 diagnosa.jlabel13().setText(con.rs.getString(12));
                 diagnosa.jlabel14().setText(con.rs.getString(13));
                 diagnosa.jlabel15().setText(con.rs.getString(14));
                 diagnosa.jtext().setText(con.rs.getString(1));
                 diagnosa.jtext1().setText(con.rs.getString(2));
                 diagnosa.getRadio14().setText("Coklat");
                 diagnosa.getRadio15().setText("Lainnya");
                 diagnosa.getRadio0().setEnabled(false);
                 diagnosa.getRadio0().setVisible(false);
                 diagnosa.getRadio1().setEnabled(false);
                 diagnosa.getRadio1().setVisible(false);
                 diagnosa.getRadio2().setEnabled(false);
                 diagnosa.getRadio2().setVisible(false);
                 diagnosa.getRadio3().setEnabled(false);
                 diagnosa.getRadio3().setVisible(false);
                 diagnosa.getRadio4().setEnabled(false);
                 diagnosa.getRadio4().setVisible(false);
                 diagnosa.getRadio5().setEnabled(false);
                 diagnosa.getRadio5().setVisible(false);
                 diagnosa.getRadio6().setEnabled(false);
                 diagnosa.getRadio6().setVisible(false);
                 diagnosa.getRadio7().setEnabled(false);
                 diagnosa.getRadio7().setVisible(false);
                 diagnosa.getRadio8().setEnabled(false);
                 diagnosa.getRadio8().setVisible(false);
                 diagnosa.getRadio9().setEnabled(false);
                 diagnosa.getRadio9().setVisible(false);
                 diagnosa.getRadio10().setEnabled(false);
                 diagnosa.getRadio10().setVisible(false);
                 diagnosa.getRadio11().setEnabled(false);
                 diagnosa.getRadio11().setVisible(false);
                 diagnosa.setVisible(true);
                 dispose(); 
                }else{
                    diagnosa.setVisible(true);
                    dispose();
                }
                
                
                 
                   
                } //panel1();
            } catch (SQLException ex) {
                Logger.getLogger(FormDiagnosa.class.getName()).log(Level.SEVERE, null, ex);
            }
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            try {
                koneksi con=new koneksi();
                con.setkoneksi();
                if(Pilihan.getSelectedItem().equals("Stroberi")){
                   int level=2;
                con.rs=con.st.executeQuery("select p.ID_Tanaman,t.Nama_Tanaman,p.Pertanyaanke_1,p.Pertanyaanke_2,p.Pertanyaanke_3,p.Pertanyaanke_4,p.Pertanyaanke_5,p.Pertanyaanke_6,p.Pertanyaanke_7,p.Pertanyaanke_8 from tanaman t inner join pertanyaan p on t.ID_Tanaman=p.ID_Tanaman where p.ID_Tanaman='"+jTextField1.getText()+"' and p.Kd_Pertanyaan='"+level+"'");
                if(con.rs.next()){
                 di.jlabel1().setText(con.rs.getString(3));
                 di.jlabel2().setText(con.rs.getString(4));
                 di.jlabel3().setText(con.rs.getString(5));
                 di.jlabel4().setText(con.rs.getString(6));
                 di.jlabel5().setText(con.rs.getString(7));
                 di.jlabel6().setText(con.rs.getString(8));
                 di.jlabel7().setText(con.rs.getString(9));
                 di.jlabel11().setText(con.rs.getString(10));
                 di.jtext().setText(con.rs.getString(1));
                 di.jtext1().setText(con.rs.getString(2));
                 di.setVisible(true);
                 dispose();
                } 
                }else if(Pilihan.getSelectedItem().equals("Jeruk")){
                    int level=4;
                con.rs=con.st.executeQuery("select p.ID_Tanaman,t.Nama_Tanaman,p.Pertanyaanke_1,p.Pertanyaanke_2,p.Pertanyaanke_3,p.Pertanyaanke_4,p.Pertanyaanke_5,p.Pertanyaanke_6,p.Pertanyaanke_7,p.Pertanyaanke_8,p.Pertanyaanke_9 from tanaman t inner join pertanyaan p on t.ID_Tanaman=p.ID_Tanaman where p.ID_Tanaman='"+jTextField1.getText()+"' and Kd_Pertanyaan='"+level+"'");
                if(con.rs.next()){
                    jButton6.setEnabled(false);
                 di.jlabel1().setText(con.rs.getString(7));
                 di.jpilih().setText("hijau");
                 di.jpilih1().setText("abu kehijauan");
                 di.jpilih2().setText("seperti biasanya");
                 di.jlabel2().setText(con.rs.getString(8));
                 di.jlabel3().setText(con.rs.getString(3));
                 di.jlabel4().setText(con.rs.getString(5));
                 di.jlabel5().setText(con.rs.getString(6));
                 di.jlabel6().setText(con.rs.getString(4));
                 di.jlabel7().setText(con.rs.getString(9));
                 di.jlabel11().setText(con.rs.getString(10));
                 di.jlabel12().setText(con.rs.getString(11));
                 di.jpilih3().setText("ya");
                 di.jpilih4().setText("tidak");
                 di.jpilih5().setText("retakan pada batang");
                 di.jpilih6().setText("tunas tidak segar");
                 di.jpilih7().setText("berjamur Fusarium sp");
                 di.jtext().setText(con.rs.getString(1));
                 di.jtext1().setText(con.rs.getString(2));
                 di.setVisible(true);
                 dispose();
                }
                }else{
                     int level=6;
                con.rs=con.st.executeQuery("select p.ID_Tanaman,t.Nama_Tanaman,p.Pertanyaanke_1,p.Pertanyaanke_2,p.Pertanyaanke_3,p.Pertanyaanke_4,p.Pertanyaanke_5,p.Pertanyaanke_6,p.Pertanyaanke_7,p.Pertanyaanke_8,p.Pertanyaanke_9 from tanaman t inner join pertanyaan p on t.ID_Tanaman=p.ID_Tanaman where p.ID_Tanaman='"+jTextField1.getText()+"' and Kd_Pertanyaan='"+level+"'");
                if(con.rs.next()){
                     di.jlabel1().setText(con.rs.getString(3));
                 di.jlabel2().setText(con.rs.getString(4));
                 di.jlabel3().setText(con.rs.getString(5));
                 di.jlabel4().setText(con.rs.getString(6));
                 di.jlabel5().setText(con.rs.getString(7));
                 di.jlabel6().setText(con.rs.getString(8));
                 di.jlabel7().setText(con.rs.getString(9));
                 di.jlabel11().setText(con.rs.getString(10));
                 di.jtext().setText(con.rs.getString(1));
                 di.jtext1().setText(con.rs.getString(2));
                 di.jpilih().setText("ya");
                 di.jpilih1().setText("tidak");
                 di.jpilih3().setText("ya");
                 di.jpilih4().setText("tidak");
                 di.jpilih5().setVisible(false);
                 di.jpilih6().setVisible(false);
                 di.jpilih7().setVisible(false);
                 di.jpilih2().setVisible(false);
                 di.setVisible(true);
                 dispose();
                }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(FormDiagnosa.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDiagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDiagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDiagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDiagnosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDiagnosa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Pilihan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
